<div class="container mx-auto my-10">

<?php if ($this->tarea): ?>
    <h1 class="text-center text-3xl font-semibold mb-4">Detalles de la Tarea</h1>
    <div class="bg-white rounded-lg shadow divide-y divide-gray-200 max-w-sm mx-auto">
        <div class="px-6 py-4">
            <div class="flex justify-between">
                <span class="font-semibold text-lg"><?php echo ($this->tarea['Titulo']); ?></span>
                <span class="text-gray-500 text-xs">Fecha: <?php echo ($this->tarea['Fecha']); ?></span><br>
            </div>
            
            <div class="flex justify-between">
            <span class="text-gray-500 text-xs">De: <?php echo ($this->tarea['Hora_inicio']); ?> hasta: <?php echo ($this->tarea['Hora_final']); ?></span>
            </div>
            <p class="text-gray-700"><?php echo ($this->tarea['Descripcion']); ?></p>
            <div class="mt-4 flex items-center justify-between">
                <p class="text-sm font-medium text-gray-500">Status: <span class="text-green-600"><?php echo ($this->tarea['Status']); ?></span></p>
                <a href="<?php echo $this->baseUrl(); ?>/tarea/edita?id=<?php echo $tarea['Id'];?>"class="text-blue-500 hover:text-blue-700 edit-btn">Editar</a>
            </div>
        </div>
    </div>
    <a href="<?php echo $this->baseUrl(); ?>/tarea">Volver a la lista</a>
<?php else: ?>
    <p><?php echo ($this->mensaje); ?></p>
    <a href="<?php echo $this->baseUrl(); ?>/tarea">Volver a la lista</a>
<?php endif; ?>
</div>