<div class="container mx-auto my-10">

<h1 class="text-center text-3xl font-semibold mb-4">Lista de Tareas</h1>

<div class="md:w-1/2 mx-auto">
<?php if (is_array($this->tareas) && count($this->tareas) > 0): ?>
    <ul>
        <?php foreach ($this->tareas as $tarea): ?>
            <li class="border-b border-gray-200 flex items-center justify-between py-4">
                <strong><?php echo $tarea['Titulo']; ?></strong>
                <p><?php echo $tarea['Status']; ?></p>
                <button class="text-blue-500 hover:text-blue-700 edit-btn">Editar</button>
                <button class="text-red-500 hover:text-red-700 mr-2 delete-btn">Eliminar</button>
            </li>
          
                <!--
            <p>Descripción: <?php echo $tarea['Descripcion']; ?></p>
            <p>Usuario: <?php echo $tarea['Usuario']; ?></p>
                <p>Status: <?php echo $tarea['Status']; ?></p>
                <p>Fecha: <?php echo $tarea['Fecha']; ?></p>
                <p>Hora de inicio: <?php echo $tarea['Hora_inicio']; ?></p>
                <p>Hora de finalización: <?php echo $tarea['Hora_final']; ?></p>-->
            
        <?php endforeach; ?>
    </ul>
<?php else: ?>
    <p>No hay tareas disponibles.</p>
<?php endif; ?>
</div>
<h1 class="text-center text-3xl font-semibold mb-4">Añadir Nueva Tarea</h1>
<form method="post" action="/Todolist/web/tarea/add" class="max-w-sm mx-auto">
<div class="relative z-0 w-full mb-5 group">
    <input type="text" id="titulo" name="titulo" class="block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer" placeholder=" " required><br>
    <label for="titulo" class="peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:start-0 rtl:peer-focus:translate-x-1/4 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">Título:</label>
</div>
<div class="relative z-0 w-full mb-5 group">
    <input type="text" id="descripcion" name="descripcion"  class="block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer" placeholder=" " required><br>
    <label for="descripcion" class="peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:start-0 rtl:peer-focus:translate-x-1/4 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">Descripción:</label>
   
</div>
<div class="relative z-0 w-full mb-5 group">
    <input type="text" id="usuario" name="usuario" class="block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer" placeholder=" " required><br>
    <label for="usuario" class="peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:start-0 rtl:peer-focus:translate-x-1/4 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">Usuario:</label>

</div>
<div class="relative z-0 w-full mb-5 group">
    <input type="text" id="status" name="status" class="block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer" placeholder=" " required><br>
    <label for="status" class="peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:start-0 rtl:peer-focus:translate-x-1/4 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">Status:</label>
    
</div>
<div class="relative z-0 w-full mb-5 group">
    <input type="date" id="fecha" name="fecha" class="block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer" placeholder=" " required><br>
    <label for="fecha" class="peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:start-0 rtl:peer-focus:translate-x-1/4 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">Fecha:</label>
    
</div>
<div class="relative z-0 w-full mb-5 group">
    <input type="time" id="horaInicio" name="horaInicio" class="block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer" placeholder=" " required><br>
    <label for="horaInicio" class="peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:start-0 rtl:peer-focus:translate-x-1/4 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">Hora de Inicio:</label>
    
</div>
<div class="relative z-0 w-full mb-5 group">
    <input type="time" id="horaFin" name="horaFin" class="block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer" placeholder=" " required><br>
    <label for="horaFin" class="peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:start-0 rtl:peer-focus:translate-x-1/4 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">Hora de Finalización:</label>
    
</div>
    <input type="submit" value="Añadir Tarea" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
</form>
</div>
